classes:
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client
- system.salt.minion.cert.etcd_client
- cluster.virtual-mcp11-k8s-calico.infra
parameters:
  _param:
    kubernetes_calicoctl_image: docker-prod-virtual.sandbox.mirantis.net/mirantis/projectcalico/calico/ctl:latest
    kubernetes_calico_image: docker-prod-virtual.sandbox.mirantis.net/mirantis/projectcalico/calico/node:latest
    kubernetes_calico_cni_image: docker-prod-virtual.sandbox.mirantis.net/mirantis/projectcalico/calico/cni:latest
    kubernetes_hyperkube_image: docker-prod-virtual.sandbox.mirantis.net/mirantis/kubernetes/hyperkube-amd64:v1.5.4-5
  docker:
    host:
      pkgs:
        - docker
        - python-docker-py
  kubernetes:
    pool:
      network:
        etcd:
          ssl:
            enabled: true
        image: ${_param:kubernetes_calico_image}
        calicoctl:
          image: ${_param:kubernetes_calicoctl_image}
        cni:
          image: ${_param:kubernetes_calico_cni_image}
    common:
      hyperkube:
        image: ${_param:kubernetes_hyperkube_image}
  linux:
    network:
      resolv:
        dns:
          - 10.254.0.10
          - 172.18.176.4
          - 172.18.176.7
      interface:
      interface:
        eth1:
          route:
            kubernetes_services:
              address: 10.254.0.0
              netmask: 255.255.0.0
              gateway: ${_param:single_address}
