classes:
- system.linux.system.single
- system.openssh.server.team.lab
- system.openssh.server.team.stacklight
- system.openssh.server.team.tcpcloud
- system.openssh.server.team.mcp_qa
- system.rsyslog.client.single
- system.telegraf.agent
- cluster.virtual-mcp11-k8s-calico.kubernetes
- cluster.virtual-mcp11-k8s-calico.monitoring
- cluster.virtual-mcp11-k8s-calico.swarm
- cluster.overwrite
parameters:
  _param:
    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 172.16.10.100
    infra_config_deploy_address: 192.168.10.100

    cluster_domain: virtual-mcp11-k8s-calico.local
    cluster_name: virtual-mcp11-k8s-calico
    apt_mk_version: nightly
  linux:
    network:
      resolv:
        dns:
          - 172.18.176.4
          - 172.18.176.7
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
      interface:
        eth1:
          enabled: true
          type: eth
          proto: manual
          address: ${_param:single_address}
          netmask: 255.255.255.0
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
  telegraf:
    agent:
      enabled: true
      interval: 15
      round_interval: false
      metric_batch_size: 1000
      metric_buffer_limit: 10000
      collection_jitter: 2
      output:
        prometheus_client:
          bind:
            address: 0.0.0.0
            port: 9126
          engine: prometheus
